### ISSUE TITLE
About the implementation of the 50Salads and Breakfast datasets

### ISSUE THREAD

**Issue by wangxiujielalala** [debadityaroy/LatentGoal#1]
Thank you for sharing. I would like to ask, where is the code for the specific implementation of 50 Salads and Breakfast mentioned in your paper? What special treatments do these two datasets require?

**Comment by debadityaroy** [comment]
Hi, 

Thanks for your interest. The I3D features were obtained from this repo for both 50Salads and Breakfast.

[https://github.com/yabufarha/ms-tcn]

Download the [data](https://mega.nz/#!O6wXlSTS!wcEoDT4Ctq5HRq_hV-aWeVF1_JB3cacQBQqOLjCIbc8) folder, which contains the features and the ground truth labels. (~30GB) (If you cannot download the data from the previous link, try to download it from [here](https://zenodo.org/record/3625992#.Xiv9jGhKhPY))

**Comment by wangxiujielalala** [comment]
As I read your paper, I noticed that the code you gave was only the processing and implementation of the EPIC-KITCHENS55 dataset. I noticed that the data organization format for the 50Salads and Breakfast datasets was not the same as the format of the EPIC-KITCHENS55 dataset, for example, the 50Salads and Breakfast datasets did not have separate comments on verbs, nouns, etc., and I was confused by the treatment of these two datasets. Is it convenient for you to publish the implementation of this code? Also, what is the meaning of the word "obs_seg" in the code? I look forward to hearing from you.

**Comment by debadityaroy** [comment]
Hi
1. 'obs_seg' refers to observed segment or observed duration.2. For the 50Salads and Breakfast dataset, you will just have actions instead of verbs or nouns.
2. I have posted the code for training on Breakfast dataset using I3D features.[https://github.com/debadityaroy/LatentGoal/blob/main/i3d_latent_goal_bf.py](https://github.com/debadityaroy/LatentGoal/blob/main/i3d_latent_goal_bf.py)
